# Generated by Django 6.0.3 on 2026-05-12 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('bibcode', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='Bibcode')),
                ('title', models.TextField(verbose_name='Titulo')),
                ('author', models.JSONField(verbose_name='Autor/es')),
                ('abstract', models.TextField(verbose_name='Resumen')),
                ('pubdate', models.DateField(verbose_name='Fecha de Publicación')),
                ('keywords', models.JSONField(null=True, verbose_name='Palabras clave')),
                ('vect_text', models.JSONField(verbose_name='Texto Vectorizado')),
                ('citation_count', models.IntegerField(verbose_name='No. de Citas')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Like')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardado',
                'verbose_name_plural': 'Guardados',
                'db_table': 'GUARDADO',
            },
        ),
    ]
