# Generated by Django 6.0.3 on 2026-05-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0002_alter_saved_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='keywords',
        ),
    ]
