# Generated by Django 6.0.5 on 2026-05-28 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0003_remove_saved_keywords'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('interests', models.JSONField(default=list)),
                ('viewed_articles', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'USER_PROFILE',
            },
        ),
    ]
