# Generated by Django 6.0.5 on 2026-05-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weights',
            field=models.JSONField(default=list),
        ),
    ]
